var DISQUS=function(a){var e={AssertionError:function(a){this.message=a}};e.AssertionError.prototype.toString=function(){return"Assertion Error: "+(this.message||"[no message]")};e.assert=function(a,f){if(!a)throw new e.AssertionError(f);};var f=[];e.define=function(l,i){typeof l==="function"&&(i=l,l="");for(var d=l.split("."),c=d.shift(),g=e,k=(i||function(){return{}}).call({overwrites:function(c){c.__overwrites__=!0;return c}},a);c;)g=g[c]?g[c]:g[c]={},c=d.shift();for(var r in k)k.hasOwnProperty(r)&&
(k.__overwrites__||g[r]!==null&&e.assert(!g.hasOwnProperty(r),"Unsafe attempt to redefine existing module with "+r),g[r]=k[r],f.push(function(c,d){return function(){delete c[d]}}(g,r)));return g};e.use=function(a){return e.define(a)};e.cleanup=function(){for(var a=0;a<f.length;a++)f[a]()};return e}(this);
DISQUS.define(function(a,e){var f=a.document,l=f.getElementsByTagName("head")[0]||f.body,i={running:!1,timer:null,queue:[]};DISQUS.defer=function(d,c){function g(){var c=i.queue;if(c.length===0)i.running=!1,clearInterval(i.timer);for(var d=0,g;g=c[d];d++)g[0]()&&(c.splice(d--,1),g[1]())}i.queue.push([d,c]);g();if(!i.running)i.running=!0,i.timer=setInterval(g,100)};DISQUS.each=function(d,c){var g=d.length,a=Array.prototype.forEach;if(isNaN(g))for(var e in d)d.hasOwnProperty(e)&&c(d[e],e,d);else if(a)a.call(d,
c);else for(a=0;a<g;a++)c(d[a],a,d)};DISQUS.serializeArgs=function(d){var c=[];DISQUS.each(d,function(d,a){d!==e&&c.push(a+(d!==null?"="+encodeURIComponent(d):""))});return c.join("&")};DISQUS.serialize=function(d,c,g){c&&(d+=~d.indexOf("?")?d.charAt(d.length-1)=="&"?"":"&":"?",d+=DISQUS.serializeArgs(c));if(g)return c={},c[(new Date).getTime()]=null,DISQUS.serialize(d,c);c=d.length;return d.charAt(c-1)=="&"?d.slice(0,c-1):d};DISQUS.require=function(d,c,g,a,e){function i(b){if(b.type=="load"||/^(complete|loaded)$/.test(b.target.readyState))a&&
a(),m&&clearTimeout(m),DISQUS.bean.remove(b.target,s,i)}var p=f.createElement("script"),s=p.addEventListener?"load":"readystatechange",m=null;p.src=DISQUS.serialize(d,c,g);p.async=!0;p.charset="UTF-8";(a||e)&&DISQUS.bean.add(p,s,i);e&&(m=setTimeout(function(){e()},2E4));l.appendChild(p);return DISQUS};DISQUS.requireStylesheet=function(d,c,g){var a=f.createElement("link");a.rel="stylesheet";a.type="text/css";a.href=DISQUS.serialize(d,c,g);l.appendChild(a);return DISQUS};DISQUS.requireSet=function(d,
c,a){var k=d.length;DISQUS.each(d,function(d){DISQUS.require(d,{},c,function(){--k===0&&a()})})};DISQUS.injectCss=function(d){var c=f.createElement("style");c.setAttribute("type","text/css");d=d.replace(/\}/g,"}\n");a.location.href.match(/^https/)&&(d=d.replace(/http:\/\//g,"https://"));c.styleSheet?c.styleSheet.cssText=d:c.appendChild(f.createTextNode(d));l.appendChild(c)}});
DISQUS.define(function(a,e){var f=a.document,l=0,i={"0.0":{},"1.0":{}};DISQUS.config={};DISQUS.blocks={theme:{},defaults:{}};DISQUS.status=null;DISQUS.settings={store_:{},schema_:{"disqus.version":{type:"str"},"disqus.domain":{type:"str"},"disqus.debug":{type:"bool"},"disqus.minified":{type:"bool"},"disqus.readonly":{type:"bool"},"disqus.recaptcha.key":{type:"str"},"disqus.facebook.appId":{type:"str"},"disqus.facebook.apiKey":{type:"str"},"disqus.urls.main":{type:"str"},"disqus.urls.media":{type:"str"},
"disqus.urls.sslMedia":{type:"str"},"disqus.urls.realtime":{type:"str"},"disqus.urls.uploads":{type:"str"},"disqus.urls.unmerged":{type:"str"}}};DISQUS.settings.store_={"disqus.recaptcha.key":"6LdKMrwSAAAAAPPLVhQE9LPRW4LUSZb810_iaa8u","disqus.urls.media":"http://mediacdn.disqus.com/1337405903","disqus.urls.main":"http://disqus.com","disqus.urls.uploads":"http://media.disqus.com/uploads","disqus.urls.realtime":"http://rt.disqus.com/forums/realtime-cached.js","disqus.urls.unmerged":"http://disqus.com/embed/profile/unmerged_profiles/",
"disqus.urls.sslMedia":"https://securecdn.disqus.com/1337405903","disqus.domain":"disqus.com","disqus.version":"1337405903","disqus.debug":!1,"disqus.minified":!0};DISQUS.settings.add=function(d,c,a){DISQUS.assert(DISQUS.settings.schema_[d]==null||a,"Unsafe attempt to update settings schema.");DISQUS.assert(c.type!=null,"Missing required property 'key'.");DISQUS.settings.schema_[d]=c;return DISQUS.settings};DISQUS.settings.get=function(d,c){var a=DISQUS.settings.schema_[d];DISQUS.assert(a!=null,"Undefined key '"+
d+"'.");var k=DISQUS.settings.store_[d];if(k==null)return c;if(a.values&&!a.values.length){var e={};DISQUS.each(a.values,function(c,d){e[c]=d});return e[k]}return k};DISQUS.settings.set=function(d,c){var a=DISQUS.settings.schema_[d],e;DISQUS.assert(a!=null,"Undefined key '"+d+"'.");e=function(d){for(var a=0,g;g=d[a];a++){if(g=="str"&&typeof c=="string")return!0;if(g=="bool"&&typeof c=="boolean")return!0;if(g=="int"&&typeof c=="number")return!0;if(g=="obj"&&typeof c=="object")return!0}return!1}(typeof a.type==
"string"?[a.type]:a.type);DISQUS.assert(e,"Invalid type for rule '"+d+"'.");a.values&&DISQUS.assert(DISQUS.contains(a.values,c),"Value is not acceptable.");a.rule&&DISQUS.assert(a.rule(c,d),"Value didn't pass schema's rule.");DISQUS.settings.store_[d]=a.values&&!a.values.length?a.values[c]:c};DISQUS.isBrowser=function(d){var c=a.navigator.userAgent,g=/(iPhone|Android|iPod|iPad|webOS|Mobile Safari|Windows Phone)/i;switch(d){case "ie":return/msie/i.test(c)&&!/opera/i.test(c);case "ie6":return!a.XMLHttpRequest;
case "ie7":return/msie/i.test(c)&&!/opera/i.test(c)&&parseInt(/MSIE\s(\d+\.\d+)/.exec(c)[1],10)==7;case "webkit":return~c.indexOf("AppleWebKit/");case "opera":return!(!a.opera||!a.opera.buildNumber);case "gecko":return~c.indexOf("Gecko/");case "safari":return~c.indexOf("Safari/");case "chrome":return~c.indexOf("Chrome/");case "mobile":return g.test(c);case "quirks":return f.compatMode==="BackCompat";default:return!1}};DISQUS.api=function(d,c){var a=DISQUS.comm&&DISQUS.comm.Default.recover();if(a){if(!c.type)c.type=
"GET";if(!c.success)c.success=function(){};if(!c.failure)c.failure=function(){};if(!c.data)c.data={};a.api(d,c.data,c.type,c.success,c.failure)}else DISQUS.once("loader.onDefaultChannelReady",function(){DISQUS.api(d,c)})};DISQUS.each(["bind","once","unbind","unbindAll","trigger"],function(d){DISQUS[d]=function(c,a){var e;c&&(c=c.replace(".","_"));switch(d){case "bind":DISQUS.bean.add(DISQUS,c,a);break;case "once":e=function(){DISQUS.unbind(c,e);a.apply(this,arguments)};DISQUS.bind(c,e);break;case "unbind":DISQUS.bean.remove(DISQUS,
c,a);break;case "unbindAll":DISQUS.bean.remove(DISQUS,c);break;case "trigger":DISQUS.bean.fire(DISQUS,c,[a])}}});DISQUS.contains=function(a,c){if(a.length){for(var g=0,e=a.length;g<e;g++)if(a[g]==c)return!0;return!1}for(g in a)if(a.hasOwnProperty(g)&&g==c)return!0;return!1};DISQUS.empty=function(a){for(var c in a)if(a.hasOwnProperty(c))return!1;return!0};DISQUS.extend=function(){var a,c;arguments.length<=1?(a=DISQUS,c=[arguments[0]||{}]):(a=arguments[0]||{},c=Array.prototype.slice.call(arguments,
1));DISQUS.each(c,function(c){DISQUS.each(c,function(c,g){a[g]=c})});return a};DISQUS.getGuid=function(){return l++};DISQUS.partial=function(){var a=arguments[0],c=Array.prototype.slice.call(arguments,1);return function(){for(var g=Array.prototype.slice.call(arguments),k=[],f=0,i=c.length;f<i;f++)k.push(c[f]===e?g.shift():c[f]);for(;g.length>0;)k.push(g.shift());return a.apply(this,k)}};DISQUS.sdk=function(a){function c(c){return function(){function g(f){c!=f.name||a!=f.version||(f.func.apply({},
e),DISQUS.unbind("loader.onSDKMethodReady",g))}var e=Array.prototype.slice.call(arguments);DISQUS.bind("loader.onSDKMethodReady",g)}}var g=i[a||"1.0"];DISQUS.assert(g!==e,"version is not supported.");if(!DISQUS.empty(g))return g;g=DISQUS.settings.get("disqus.debug")?"/js/src/sdk/":"/build/system/sdk/";DISQUS.require(DISQUS.settings.get("disqus.urls.media")+g+a+".js");return{getThread:c("getThread"),getSession:c("getSession")}};DISQUS.sdk.add=function(a,c,g){DISQUS.assert(i[c]!==e,"version is not supported.");
i[c][a]=g;DISQUS.trigger("loader.onSDKMethodReady",{name:a,version:c,func:g})};DISQUS.useSSL=function(d){var c,g,e;if(a.location.href.match(/^https/))if(d){c=["disqus_url","realtime_url","uploads_url"];for(e=0;g=c[e];e++)d[g]=d[g].replace(/^http/,"https");d.media_url=d.ssl_media_url}else{c=["disqus.urls.main","disqus.urls.realtime","disqus.urls.uploads"];for(e=0;g=c[e];e++)DISQUS.settings.set(g,DISQUS.settings.get(g).replace(/^http/,"https"));DISQUS.settings.set("disqus.urls.media",DISQUS.settings.get("disqus.urls.sslMedia"))}};
DISQUS.useSSL();DISQUS.ready=function(a){function c(){var a=DISQUS.settings.get("disqus.urls.media"),c=a+"/js/src/embed/custom/",d=a+"/build/system/",e=DISQUS.settings.get("disqus.debug"),f=DISQUS.settings.get("disqus.urls.media"),i;DISQUS.status="loading";e?(i=a+"/styles/dtpl/defaults.css",a=[c+"strings.js",c+"dtpl.js",c+"actions.js",c+"validators.js",c+"utils.js",c+"db.js",c+"nodes.js",c+"sandbox.js",c+"tooltip.js",c+"comm.js",c+"ui.js",c+"sso.js",c+"compat.js",c+"facebook.js",c+"tracking.js",d+
"defaults.js",a+"/js/src/lib/easyxdm.js",a+"/js/src/json.js",a+"/js/src/sdk/1.0.js"],DISQUS.config.includeStacktrace&&a.push(f+"/js/src/lib/stacktrace.js")):(i=d+"/defaults.css",a=[d+"disqus.js"]);DISQUS.requireStylesheet(i);DISQUS.requireSet(a,e,function(){DISQUS.status="ready";DISQUS.trigger("loader.onFilesReady")})}if(DISQUS.status=="ready")a();else DISQUS.once("loader.onFilesReady",function(){a()});DISQUS.status===null&&c()};DISQUS.addBlocks=function(a,c){if(c)return function(){var a=DISQUS.blocks;
DISQUS.blocks={};c();DISQUS.blocks=DISQUS.extend(a,{theme:DISQUS.blocks})}();var e={Builder:DISQUS.strings.Builder,renderBlock:DISQUS.renderBlock,each:DISQUS.each,extend:DISQUS.extend,blocks:DISQUS.blocks[a||"defaults"],interpolate:DISQUS.strings.interpolate};return function(a){a(e)}};DISQUS.renderBlock=function(a,c){var g=a;typeof a==="string"&&(g=DISQUS.getBlock(a));if(g===e)throw"Block "+a+" was not found!";return DISQUS.sandbox.wrap(a,g,c)};DISQUS.getBlock=function(a){return DISQUS.blocks.theme[a]||
DISQUS.blocks.defaults[a]};DISQUS.window={getSize:function(){return typeof a.innerWidth=="number"?[a.innerWidth,a.innerHeight]:f.documentElement?[f.documentElement.clientWidth||f.body.clientWidth,f.documentElement.clientHeight||f.body.clientHeight]:[-1,-1]},getScrollPosition:function(){var a=f.documentElement;return a&&(a.scrollTop||a.scrollWidth)?[a.scrollWidth,a.scrollTop||f.body.scrollTop]:[f.body.scrollWidth,f.body.scrollTop]}}});
(function(a){function e(a){a=a.relatedTarget;if(!a)return a===null;var b;if(b=a!=this)if(b=a.prefix!="xul")if(b=!/document/.test(this.toString())){var c;a:for(a=a.parentNode;a!==null;){if(a==this){c=!0;break a}a=a.parentNode}b=!c}return b}var f=1,l={},i={},d=/over|out/,c=/[^\.]*(?=\..*)\.|.*/,g=/\..*/,k=((a.document||{}).documentElement||{}).addEventListener,r=k?"addEventListener":"attachEvent",x=function(a,b){return a.__uid=b||a.__uid||f++},p=function(a){a=x(a);return l[a]=l[a]||{}},s=k?function(a,
b,c,j){a[j?"addEventListener":"removeEventListener"](b,c,!1)}:function(a,b,c,j,h){h&&j&&(a["_on"+h]=a["_on"+h]||0);a[j?"attachEvent":"detachEvent"]("on"+b,c)},m=function(b,c,h){return function(d){d=j(d||((this.ownerDocument||this.document||this).parentWindow||a).event);return c.apply(b,[d].concat(h))}},b=function(a,b,c,j,h){return function(d){if(j?j.apply(this,arguments):k||d&&d.propertyName=="_on"+c||!d)b.apply(a,Array.prototype.slice.call(arguments,d?0:1).concat(h))}},q=function(a,j,d,e){var f=
j.replace(g,""),B=p(a),B=B[f]||(B[f]={}),l=d,j=x(d,j.replace(c,""));if(B[j])return a;var n=o[f];n&&(d=n.condition?b(a,d,f,n.condition):d,f=n.base||f);d=(n=h[f])?m(a,d,e):b(a,d,f,!1,e);n=k||n;if(f=="unload")var A=d,d=function(){t(a,f,d)&&A()};a[r]&&s(a,n?f:"propertychange",d,!0,!n&&f);B[j]=d;d.__uid=j;d.__originalFn=l;return f=="unload"?a:i[x(a)]=a},t=function(a,b,j){var w;var d,e,f=p(a),i=b.replace(g,"");if(!f||!f[i])return a;w=(b=b.replace(c,""))?b.split("."):[j.__uid],b=w;for(e=b.length;e--;)d=
b[e],j=f[i][d],delete f[i][d],a[r]&&(i=o[i]?o[i].base:i,d=k||h[i],s(a,d?i:"propertychange",j,!1,!d&&i));return a},u=function(a,b,c){return function(d){for(var j=typeof a=="string"?c(a,this):a,h=d.target;h&&h!=this;h=h.parentNode)for(var e=j.length;e--;)if(j[e]==h)return b.apply(h,arguments)}},v=function(a,b,c,j,d){if(typeof b=="object"&&!c)for(var h in b)b.hasOwnProperty(h)&&v(a,h,b[h]);else{h=typeof c=="string";for(var e=(h?c:b).split(" "),c=h?u(b,j,d):c,f=e.length;f--;)q(a,e[f],c,Array.prototype.slice.call(arguments,
h?4:3))}return a},y=function(a,b,j){var d,h,e,f=typeof b=="string",i=f&&b.replace(c,""),o=t,n=p(a);if(f&&/\s/.test(b)){b=b.split(" ");for(e=b.length-1;y(a,b[e])&&e--;);return a}h=f?b.replace(g,""):b;if(!n||f&&!n[h]){if(n&&i)for(d in n)if(n.hasOwnProperty(d))for(e in n[d])n[d].hasOwnProperty(e)&&e===i&&o(a,[d,i].join("."));return a}if(typeof j=="function")o(a,h,j);else if(i)o(a,b);else for(d in o=h?o:y,b=f&&h,h=h?j||n[h]||h:n,h)h.hasOwnProperty(d)&&(o(a,b||d,h[d]),delete h[d]);return a},C=k?function(b,
c,d){evt=document.createEvent(b?"HTMLEvents":"UIEvents");evt[b?"initEvent":"initUIEvent"](c,!0,!0,a,1);d.dispatchEvent(evt)}:function(a,b,c){a?c.fireEvent("on"+b,document.createEventObject()):c["_on"+b]++},z=function(a,b,c){var d=p(b),j;x(a);d=c?d[c]:d;for(j in d)d.hasOwnProperty(j)&&(c?v:z)(a,c||b,c?d[j].__originalFn:j);return a},j=function(a){var b={};if(!a)return b;var c=a.type,h=a.target||a.srcElement;b.preventDefault=j.preventDefault(a);b.stopPropagation=j.stopPropagation(a);b.target=h&&h.nodeType==
3?h.parentNode:h;if(~c.indexOf("key"))b.keyCode=a.which||a.keyCode;else if(/click|mouse|menu/i.test(c)){b.rightClick=a.which==3||a.button==2;b.pos={x:0,y:0};if(a.pageX||a.pageY)b.clientX=a.pageX,b.clientY=a.pageY;else if(a.clientX||a.clientY)b.clientX=a.clientX+document.body.scrollLeft+document.documentElement.scrollLeft,b.clientY=a.clientY+document.body.scrollTop+document.documentElement.scrollTop;d.test(c)&&(b.relatedTarget=a.relatedTarget||a[(c=="mouseover"?"from":"to")+"Element"])}for(var e in a)e in
b||(b[e]=a[e]);return b};j.preventDefault=function(a){return function(){a.preventDefault?a.preventDefault():a.returnValue=!1}};j.stopPropagation=function(a){return function(){a.stopPropagation?a.stopPropagation():a.cancelBubble=!0}};var h={click:1,dblclick:1,mouseup:1,mousedown:1,contextmenu:1,mousewheel:1,DOMMouseScroll:1,mouseover:1,mouseout:1,mousemove:1,selectstart:1,selectend:1,keydown:1,keypress:1,keyup:1,orientationchange:1,touchstart:1,touchmove:1,touchend:1,touchcancel:1,gesturestart:1,gesturechange:1,
gestureend:1,focus:1,blur:1,change:1,reset:1,select:1,submit:1,load:1,unload:1,beforeunload:1,resize:1,move:1,DOMContentLoaded:1,readystatechange:1,error:1,abort:1,scroll:1},o={mouseenter:{base:"mouseover",condition:e},mouseleave:{base:"mouseout",condition:e},mousewheel:{base:/Firefox/.test(navigator.userAgent)?"DOMMouseScroll":"mousewheel"}},n={add:v,remove:y,clone:z,fire:function(a,b,d){var j,e,f=b.split(" ");for(e=f.length;e--;){var b=f[e].replace(g,""),i=h[b],o=f[e].replace(c,""),n=p(a)[b];if(o){o=
o.split(".");for(j=o.length;j--;)n&&n[o[j]]&&n[o[j]].apply(a,[!1].concat(d))}else if(!d&&a[r])C(i,b,a);else for(j in n)n.hasOwnProperty(j)&&n[j].apply(a,[!1].concat(d))}return a}};a.attachEvent&&v(a,"unload",function(){for(var b in i)if(i.hasOwnProperty(b)){var c=y(i[b]).__uid;c&&(delete i[c],delete l[c])}a.CollectGarbage&&CollectGarbage()});var A=a.bean;n.noConflict=function(){a.bean=A;return this};a.bean=n})(this);
(function(a,e){function f(){this.c={}}function l(a){u=[];s=0;for(y=a.length;s<y;s++)u[s]=a[s];return u}function i(a){for(;a=a.previousSibling;)if(a.nodeType==1)break;return a}function d(a,b,c,d,j,h,e,f,i,k,l){var A,m;if(b&&this.tagName.toLowerCase()!==b)return!1;if(c&&(A=c.match(o))&&A[1]!==this.id)return!1;if(c&&(z=c.match(n)))for(s=z.length;s--;)if(a=z[s].slice(1),!(D.g(a)||D.s(a,RegExp("(^|\\s+)"+a+"(\\s+|$)"))).test(this.className))return!1;if(i&&p.pseudos[i]&&!p.pseudos[i](this,l))return!1;if(d&&
!e)for(m in t=this.attributes,t)if(Object.prototype.hasOwnProperty.call(t,m)&&(t[m].name||m)==j)return this;if(d&&!g(h,this.getAttribute(j)||"",e))return!1;return this}function c(a){return G.g(a)||G.s(a,a.replace(P,"\\$1"))}function g(a,b,d){switch(a){case "=":return b==d;case "^=":return b.match(w.g("^="+d)||w.s("^="+d,RegExp("^"+c(d))));case "$=":return b.match(w.g("$="+d)||w.s("$="+d,RegExp(c(d)+"$")));case "*=":return b.match(w.g(d)||w.s(d,RegExp(c(d))));case "~=":return b.match(w.g("~="+d)||
w.s("~="+d,RegExp("(?:^|\\s+)"+c(d)+"(?:\\s+|$)")));case "|=":return b.match(w.g("|="+d)||w.s("|="+d,RegExp("^"+c(d)+"(-|$)")))}return 0}function k(a){var b=[],c=[],j,h=0,f,g,i,o,n,k=H.g(a)||H.s(a,a.split(O)),a=a.match(N),k=k.slice(0);if(!k.length)return b;g=k.pop();o=k.length&&(j=k[k.length-1].match(A))?e.getElementById(j[1]):e;if(!o)return b;n=g.match(F);f=a&&/^[+~]$/.test(a[a.length-1])?function(a){for(;o=o.nextSibling;)o.nodeType==1&&(n[1]?n[1]==o.tagName.toLowerCase():1)&&a.push(o);return a}([]):
o.getElementsByTagName(n[1]||"*");j=0;for(g=f.length;j<g;j++)if(i=d.apply(f[j],n))b[h++]=i;if(!k.length)return b;h=0;g=b.length;for(f=0;h<g;h++){i=b[h];for(j=k.length;j--;)for(;i=Q[a[j]](i,b[h]);)if(C=d.apply(i,k[j].match(F)))break;C&&(c[f++]=b[h])}return c}function r(a,b,c){c=typeof b=="string"?c(b)[0]:b||e;if(a===window||a&&a.nodeType&&(a.nodeType==1||a.nodeType==9))return!b||a!==window&&c&&c.nodeType&&(c.nodeType==1||c.nodeType==9)&&I(a,c)?[a]:[];if(a&&typeof a==="object"&&isFinite(a.length))return l(a);
if(q=a.match(A))return(v=e.getElementById(q[1]))?[v]:[];if(q=a.match(K))return l(c.getElementsByTagName(q[1]));return!1}function x(a){var b=[],c,d;c=0;a:for(;c<a.length;c++){for(d=0;d<b.length;d++)if(b[d]==a[c])continue a;b[b.length]=a[c]}return b}function p(a,b){var c=typeof b=="string"?p(b)[0]:b||e;if(!c||!a)return[];if(q=r(a,b,p))return q;return R(a,c)}var s,m,b,q,t,u,v,y,C,z,j,h=e.documentElement,o=/#([\w\-]+)/,n=/\.[\w\-]+/g,A=/^#([\w\-]+$)/,J=/^\.([\w\-]+)$/,K=/^([\w\-]+)$/,L=/^([\w]+)?\.([\w\-]+)$/,
M=/\s*([\s\+\~>])\s*/g,E=/[\s\>\+\~]/,B=/(?![\s\w\-\/\?\&\=\:\.\(\)\!,@#%<>\{\}\$\*\^'"]*\])/,N=RegExp("("+E.source+")"+B.source,"g"),O=RegExp(E.source+B.source),P=/([.*+?\^=!:${}()|\[\]\/\\])/g,F=RegExp(/^([a-z0-9]+)?(?:([\.\#]+[\w\-\.#]+)?)/.source+"("+/\[([\w\-]+)(?:([\|\^\$\*\~]?\=)['"]?([ \w\-\/\?\&\=\:\.\(\)\!,@#%<>\{\}\$\*\^]+)["']?)?\]/.source+")?("+/:([\w\-]+)(\(['"]?(\w+)['"]?\))?/.source+")?"),Q={" ":function(a){return a&&a!==h&&a.parentNode},">":function(a,b){return a&&a.parentNode==b.parentNode&&
a.parentNode},"~":function(a){return a&&a.previousSibling},"+":function(a,b,c,d){if(!a)return!1;c=i(a);d=i(b);return c&&d&&c==d&&c}};f.prototype={g:function(a){return this.c[a]||void 0},s:function(a,b){return this.c[a]=b}};var D=new f,G=new f,w=new f,H=new f,I="compareDocumentPosition"in h?function(a,b){return(b.compareDocumentPosition(a)&16)==16}:"contains"in h?function(a,b){b=b==e||b==window?h:b;return b!==a&&b.contains(a)}:function(a,b){for(;a=a.parentNode;)if(a===b)return 1;return 0},R=e.querySelector&&
e.querySelectorAll?function(a,b){if(b.getElementsByClassName&&(q=a.match(J)))return l(b.getElementsByClassName(q[1]));return l(b.querySelectorAll(a))}:function(a,c){var a=a.replace(M,"$1"),d=[],h,f=[],g;if(q=a.match(L)){j=c.getElementsByTagName(q[1]||"*");u=D.g(q[2])||D.s(q[2],RegExp("(^|\\s+)"+q[2]+"(\\s+|$)"));g=0;b=j.length;for(m=0;g<b;g++)u.test(j[g].className)&&(d[m++]=j[g]);return d}g=0;j=a.split(",");for(b=j.length;g<b;g++)f[g]=k(j[g]);g=0;for(b=f.length;g<b&&(h=f[g]);g++){var i=h;if(c!==e){i=
[];m=0;for(q=h.length;m<q&&(element=h[m]);m++)I(element,c)&&i.push(element)}d=d.concat(i)}return x(d)};p.uniq=x;p.pseudos={};var S=a.qwery;p.noConflict=function(){a.qwery=S;return this};a.qwery=p})(this,document);
(function(){DISQUS.extend({bean:bean.noConflict(),qwery:qwery.noConflict(),throttle:function(a,e,f,l){var i=(new Date).getTime();DISQUS.bean.add(a,e,function(a){var c=(new Date).getTime();c-i>=l&&(i=c,f(a))})},debounce:function(a,e,f,l){function i(a){d&&clearTimeout(d);d=setTimeout(function(){f(a,c)},l)}var d,c;c=function(){DISQUS.bean.remove(a,e,i)};DISQUS.bean.add(a,e,i)}})})();DISQUS.modules={};DISQUS.addJob=DISQUS.defer;DISQUS.getResourceURL=DISQUS.serialize;
DISQUS.lang={contains:DISQUS.contains,forEach:DISQUS.each,extend:DISQUS.extend,trim:function(a){for(var a=a.replace(/^\s\s*/,""),e=/\s/,f=a.length;e.test(a.charAt(--f)););return a.slice(0,f+1)},partial:DISQUS.partial};DISQUS.events={add:DISQUS.bean.add,remove:DISQUS.bean.remove,debounce:DISQUS.debounce};
DISQUS.browser={ie:DISQUS.isBrowser("ie"),ie6:DISQUS.isBrowser("ie6"),ie7:DISQUS.isBrowser("ie7"),webkit:DISQUS.isBrowser("webkit"),opera:DISQUS.isBrowser("opera"),gecko:DISQUS.isBrowser("gecko"),mobile:DISQUS.isBrowser("mobile"),quirks:DISQUS.isBrowser("quirks")};
DISQUS.define("cookies",function(){return{create:function(a,e,f){a=a+"="+e+"; path=/";f.domain&&(a+="; domain=."+f.domain);f.expiresIn&&(e=new Date,e.setTime(e.getTime()+f.expiresIn),a+="; expires="+e.toGMTString());document.cookie=a},read:function(a){a+="=";for(var e,f=document.cookie.split(";"),l=0;l<f.length;l++){for(e=f[l];e.charAt(0)==" ";)e=e.substring(1,e.length);if(e.indexOf(a)===0)return e.substring(a.length,e.length)}return null},erase:function(a){var e=new Date;e.setTime(e.getTime()+-864E5);
a=a+"=; path=/;expires="+e.toGMTString();document.cookie=a}}});DISQUS.define("ga",function(a){var e,f=function(f){e?e(f):a._gaq.push(f)},l={component:1,"package":2,forum:3,version:4,userType:5};return{setCaller:function(a){e=a},setAccount:function(a){f(["_setAccount",a])},setCustomVar:function(a,d){f(["_setCustomVar",l[a],a,d])},trackPageview:function(){f(["_trackPageview"])},trackEvent:function(a,d,c){f(["_trackEvent",d,a,c,1])},setDomainName:function(a){f(["_setDomainName",a])}}});
DISQUS.define("juggler",function(){var a,e,f={},l=["thread","forum","forum_id"],i=l.slice().concat(["imp","event"]),d=[],c=(new Date).getTime().toString(10)+Math.floor(Math.random()*1E6).toString(10);return{load:function(g){DISQUS.cookies.create("__jid",c,{expiresIn:18E5});e=g.url;DISQUS.each(l,function(a){f[a]=g[a]});f.imp=c;a=function(a){DISQUS.each(f,function(c,d){a[d]=f[d]});DISQUS.require(e,a,!1)};DISQUS.each(d,function(c){a(c)})},emit:function(c,e){DISQUS.each(i,function(a){if(e[a]!=null)throw"Error: cannot overwrite event context '"+
a+"'";});e.event=c;a==null?d.push(e):a(e)},impId:c}});
(function(a){function e(a,b){return a.hasAttribute?a.hasAttribute(b):a.getAttribute(b)!==null}function f(){for(var a=0,b=t.length;a<b;a++)if(e(t[a],"name")&&t[a].getAttribute("name")=="generator"&&e(t[a],"content")&&t[a].getAttribute("content")=="blogger")return!0;a=m.getElementById("Attribution1");if(a!=null&&a.innerHTML.indexOf("http://www.blogger.com")>0)return!0;return!1}function l(){var a;if(f()){a=m.getElementsByTagName("A");for(var b=0,c=a.length;b<c;b++)if(!e(a[b],"src")&&e(a[b],"name")&&
parseInt(a[b].getAttribute("name"),10)&&a[b].innerHTML==="")return a[b].getAttribute("name")}return null}function i(a){var b=0,c=0;if(!a.offsetParent)return[0,0];do b+=a.offsetLeft,c+=a.offsetTop,a=a.offsetParent;while(a);return[b,c]}function d(a){var c=b.window.getScrollPosition()[1],d=c+b.window.getSize()[1];return a>=c&&a<=d}function c(a){if(!(typeof q!="function"&&typeof a!="function")){var c={preData:"loader.onReady",preInit:"loader.onDataReady",onInit:"loader.onLibraryReady",afterRender:"loader.onTemplateReady",
onReady:"thread.onReady",onPaginate:"thread.onPaginate",onNewComment:"comment.onCreate",preReset:"thread.beforeReset"};b.config.callbacks={};b.config.page={};b.each(c,function(a,c){b.config.callbacks[c]=[]});try{(a||q).call(b.config)}catch(d){}b.each(b.config.callbacks,function(a,d){a.length!==0&&b.each(a,function(a){b.bind(c[d],a)})});b.config.callbacks=c}}function g(){var c={url:"thread.url",title:"thread.title",slug:"thread.slug",category_id:"thread.category",identifier:"thread.identifier",remote_auth_s3:"request.sso.data",
author_s3:"thread.author.sig",api_key:"forum.apiKey"};b.each({disqus_domain:"disqus.domain",disqus_category_id:"thread.category",disqus_thread_slug:"thread.slug",disqus_title:"thread.title",disqus_url:"thread.url",disqus_identifier:"thread.identifier",disqus_per_page:"thread.postsPerPage",disqus_require_moderation_s:"thread.moderatePosts",disqus_skip_auth:"thread.skipAuthRequest",disqus_def_email:"thread.defaults.email",disqus_def_name:"thread.defaults.name",disqus_default_text:"thread.defaults.placeholder",
disqus_shortname:"forum.shortname",disqus_facebook_key:"forum.facebook.key",disqus_custom_strings:"ui.translations",disqus_container_id:"ui.container",DsqLocal:"legacy.trackbacks",disqus_remote_auth_s2:"legacy.sso.data",disqus_author_s2:"legacy.thread.author.sig"},function(c,d){a[d]!=null&&b.settings.set(c,a[d])});if(a.disqus_sort!=null)b.settings.store_["thread.sort"]=a.disqus_sort;a.disqus_developer!=null&&b.settings.set("disqus.developer",!!a.disqus_developer);b.config&&b.config.page&&(b.config.page.remote_auth_s3!=
null&&b.settings.set("request.sso.data",b.config.page.remote_auth_s3),b.config.page.api_key!=null&&b.settings.set("forum.apiKey",b.config.page.api_key),b.each(c,function(a,c){b.config.page[c]!=null&&b.settings.set(a,b.config.page[c])}))}function k(){var c=a.location.hash,h=b.settings.get,e=h("legacy.trackbacks",{});b.extend(b.config,{container_id:h("ui.container","disqus_thread"),trackback_url:e.trackback_url||null,trackbacks:e.trackbacks||null,absorbStyles:!1});b.config.page={url:h("thread.url",
a.location.href),title:h("thread.title",""),slug:h("thread.slug"),sort:h("thread.sort",""),per_page:h("thread.postsPerPage",null),category_id:h("thread.category",""),developer:+h("disqus.developer",0),identifier:h("thread.identifier",""),require_mod_s:h("thread.moderatePosts"),remote_auth_s3:h("request.sso.data"),author_s3:h("thread.author.sig"),api_key:h("forum.apiKey"),disqus_version:h("disqus.version"),remote_auth_s2:h("legacy.sso.data"),author_s2:h("legacy.thread.author.sig")};if(~c.search(/comment\-\d+/))b.config.page.lazy=
"0";else{var g,e=m.getElementById(b.config.container_id);g=i(e)[1];if(e&&d(g))b.config.page.lazy="0"}if(f())b.config.page.blogger_id=l(),b.config.page.url=b.config.page.url.replace(/\?.*$/,"");if(c&&(c=c.match(/comment\-([0-9]+)/)))b.config.page.anchor_post_id=c[1];var k=a.disqus_callback;typeof k=="function"&&b.bind("thread.onReady",function(){k(a.disqus_callback_params||null)});b.config.custom_strings=h("ui.translations",{});b.extend(b.config,{domain:h("disqus.domain"),shortname:h("forum.shortname")||
b.getShortname(),facebook_key:h("forum.facebook.key",null),def_name:h("thread.defaults.name"),def_email:h("thread.defaults.email"),def_text:h("thread.defaults.placeholder",""),skip_auth:h("thread.skipAuthRequest",!1)});h=b.config.shortname+"."+b.config.domain+"/thread.js";b.config.json_url=a.location.href.match(/^https/)?"https://"+h:"http://"+h}function r(a){return Date.UTC(a.getUTCFullYear(),a.getUTCMonth(),a.getUTCDate(),a.getUTCHours(),a.getUTCMinutes(),a.getUTCSeconds(),a.getUTCMilliseconds())}
function x(){b.bind("thread.onReady",function(){function c(){f&&d(f)&&b.trigger("comments.replyViewed");g&&d(g)&&b.trigger("thread.bottomViewed")}var e=m.getElementById("dsq-reply")||m.getElementById("dsq-new-post"),f=e?b.nodes.getPosition(e)[1]+e.offsetHeight:null,e=m.getElementById("dsq-comments"),g=b.nodes.getPosition(e)[1]+e.offsetHeight;c();b.events.debounce(a,"scroll",c,250);b.resettable=!0;b.trigger("thread.onResetReady")});b.bind("thread.onReady",function(){var c=b.comm.Default.recover(),
d=r(new Date);c.log("load:start",z);c.log("load:length",d-z);try{a.jQuery&&jQuery.ui?c.log("jslib","jqueryui:"+jQuery.ui.version):a.jQuery?c.log("jslib","jquery:"+jQuery().jquery):a.Prototype?c.log("jslib","prototype:"+Prototype.Version):a.dojo?c.log("jslib","dojo:"+dojo.version.toString()):a.MooTools?c.log("jslib","mootools:"+MooTools.version):a.Ext?c.log("jslib","ext:"+Ext.version):a.YUI?c.log("jslib","yui:"+YUI.version):c.log("jslib","none")}catch(e){c.log("jslib","error")}c.flushLog(null)});b.bind("loader.onTemplateReady",
function(){var a=b.comm.Default.recover(),c=b.jsonData;c.context.switches.sigma&&a.enable(c.context.sigma_chance);a.log("hit",1);c.forum.id&&a.addMeta("info:forum_id",c.forum.id);c.thread.id&&a.addMeta("info:thread_id",c.thread.id);c.request.user_type&&a.addMeta("info:user_type",c.request.user_type);c.request.user_id&&a.addMeta("info:user_id",c.request.user_id)});b.once("thread.bottomViewed",function(){b.comm.Default.recover().log("viewed:comments",1)});b.once("comments.replyViewed",function(){b.comm.Default.recover().log("viewed:comment_box",
1)})}function p(){function a(b,c,d,e,f,h){return'<img width="'+b+'" height="'+c+'" alt="'+e+'" src="data:image/'+d+";base64,"+f+'"'+(h?'style="'+h+'"':"")+"/>"}b.jsonData={ready:!1};var c;b.require(b.config.json_url,b.config.page,!0,null,function(){c.innerHTML='There was a problem loading Disqus. For more information, please visit <a href="http://status.disqus.com">status.disqus.com</a>.'});var d=b.qwery("#dsq-content")[0]||m.createElement("div");d.id="dsq-content";d.style.display="none";c=b.qwery("#dsq-content-stub")[0]||
m.createElement("div");c.id="dsq-content-stub";c.innerHTML=b.browser.ie6?"...":a(71,17,"png","DISQUS",y.join(""))+a(16,11,"gif","...",C.join(""),"margin:0 0 3px 5px");var e=b.qwery("#"+b.config.container_id)[0];e.appendChild(d);e.appendChild(c);x();b.ready(function(){b.initThread(function(){c.style.display="none"})})}function s(c){function d(){b.trigger("loader.onDefaultChannelReady")}var e=m.getElementById("dsq-content"),f=b.settings.get("disqus.urls.media"),g=f+"/build/system/",i=f+"/build/lang/",
k=b.jsonData.forum.template.css,l=b.jsonData.forum.template.url,p=b.jsonData.context.switches,q=b.settings.get("disqus.debug"),r=b.settings.get("disqus.preview");b.trigger("loader.onDataReady");if(b.browser.mobile&&!b.jsonData.forum.mobile_theme_disabled)k=b.jsonData.forum.template.mobile.css,l=b.jsonData.forum.template.mobile.url,b.states.isMobile=!0;else if(r)k=r.styles,l=r.source;!a.disqus_no_style&&k&&b.requireStylesheet(k,{},q);k=b.jsonData.forum.stylesUrl;if(!b.jsonData.context.switches.static_styles||
q)k="http://"+b.config.domain+"/forums/"+b.config.shortname+"/styles.css";b.jsonData.forum.hasCustomStyles&&b.requireStylesheet(k,{u:b.jsonData.forum.lastUpdate});l=[l];p.new_toolbar&&(l.push(g+"/defaults.toolbar.js"),b.requireStylesheet(q?f+"/styles/dtpl/defaults.toolbar.css":g+"/defaults.toolbar.css",{},q));~a.location.search.indexOf("fb_xd_fragment")?b.require("http://connect.facebook.net/en_US/all.js"):(b.config.language?b.config.language!="en"&&l.push(i+b.config.language+".js"):b.jsonData.forum.language!=
"en"&&l.push(i+b.jsonData.forum.language+".js"),b.comm.Default.recover()||b.comm.Default.create(d).setApiKey(b.jsonData.forum.apiKey),b.requireSet(l,q,function(){b.config.custom_strings&&b.lang.extend(b.strings.translations,b.config.custom_strings);if(b.config.def_text==="")b.config.def_text=b.strings.get("Type your comment here.");b.registerActions();b.trigger("loader.onActionsReady");b.nodes.addClass(e,"clearfix");var a=e.parentNode;a.removeChild(e);e.innerHTML=b.renderBlock("thread");a.appendChild(e);
b.trigger("loader.onLibraryReady");b.dtpl.actions.fire("thread.initialize");b.trigger("loader.onTemplateReady");b.bean.add(e,"click change",function(a){for(var c=a.target,d;c&&c!=e;){if(d=b.dtpl.getAction(c,a)){a.preventDefault();d();break}c=c.parentNode}});b.nodes.container=b.nodes.get("#dsq-content");e.style.display="block";c();b.config.page.anchor_post_id&&b.nodes.scrollTo("#dsq-comment-"+b.config.page.anchor_post_id);b.dtpl.actions.fire("thread.ready")}))}var m=a.document,b=a.DISQUS,q=a.disqus_config;
b.qwery("head")[0]||b.qwery("#disqus_thread");var t=b.qwery("meta"),u=!1,v=[],y=["iVBORw0KGgoAAAANSUhEUgAAAEcAAAARCAYAAAH4YIFjAAAAGXRFWHRTb2Z0d2FyZQBB","ZG9iZSBJbWFnZVJlYWR5ccllPAAABwdJREFUeNpi/P//PwMhwAIiGBkZGeK6V8JVh9rq","dfrc0ixnEDb+wPD2rAAjMSYBBBBRisDWwKxCthIE/q8Q+A8yhCiTAAIIrCi+ZxVMZSAQ","r19UGs4IMxWd/X8Rw3/GOKDhW43fgzwF1hX7n5EJ2dSp2QFNUKcZwJ31/78CkvPBGkGG","MXidSUTWCxBAxAUAEQAcJzCvIXsDBPwsNBU2nbj+AMpdsFA8PAHsLZj3QC5D9hrIAEtN","+RMwAzRkxcB0iK3eQ6iQIRAnoMTE//8CyHwmWHQdv/7QAiZ44/ErMP383acsqNB5iMnP",
"lsFdsUZ6IU3CCCCA4AYBw8kBJgj06gGkmHJAFgPyQV4ExeQEoNgHJHUBQMoAWRzoerBe","YHgeQOJ/APIvQPkNUP4EuIdADBAGBRMQOABxQcakdSipHZldNGvL2zWHL8kD1d0HieVN","33QYqnc/EAfULNwJVw8KTniQwvjAdPz/SEwKmL1KfC5QjwEQr4e5AyVdA3P4ASCe8O3n","b1whmtib6r3IXlfpATBEFbpWH9ygJSdmBtXrOHPbyZWPXn1AqOZRwDSBS+YHo82SOQwi","ZnYMoS+EGC42nGdYzBiAnKpgGAbeA3ECkjwYQNnzH758///6o5cgofVIagy+/vgFF//y","/ecHJLn1/18AA+/teZBcPZL4eSTxBJg7AAKIaomRmpkeV2IG5UcDpMSsAM2zF4BiG9DU","FaCLQxPwBWCC/QBkg/QqoCVuEN4ASuDIaWc/DIMSItBxH0GCrkaqCVBxWO4BJWBQcK/P","mrL+I1S8H0i9h4mjFfX7GTRyIdEuHzIfZtb/Zdw3oGyQnvP/d9pNgRc+MLCwJMxxWk7A",
"I6Ar+YCWVSLLyYkJzIYlZqC6RGBhbg/lFwDlQHoDgfgALLfhjY8/X9XhpWPs/wWM7ody","MBwDylU8nOzyILYIH3cZslxBgM0cKHM+MOTAGCZnri7XCdS7ASgGLsc/fPlug9cxlrO/","wUvYxYwJwCgLwHAMcrVlqCJ9BVlchJ+7EhRyQPwAyGaAFnhgsOPMzUhQroLVAU76yp/g","Gp/vtQbTr45pwMWOp1oDQ6QQiGEi6+EJGLmah0YJQ6CVtu3ivecKYHIpE9b8BPqcDSna","wHSSu8m3eTvPyAHlzsPkDl25/wXMYAOq+XgtBFwIfn/GwCAOSq8HYCGCsNh8+hvksgYZ","IJchDkjljAKoHAKVJ6ByBbnmA5XESOL1oFIZSc9/cJkC1IukPuH/z/cw8fswdwyqcgYg","wAaVYwYbQEnDSI1LbGABEDcCC1lYS4yhfO42n+fvPm9GKsAZkfJDA7RcwwYmQM1CbpUU","ADU3AB3AjxJ7wFwAFGsAqp2A0mBDahww8Gv4Mvrf2AKXWyMzgeHbk3wwh5X/DGPkR1Oo",
"HlCmn49cGCABkL8SgZn8ANbAQQaV4ZBK6yGwgbDr3G2GNx+/gkqShMTe1V///vsnA/KY","joKECjBwMPQCW0EngOrNQWxbHQWGFA8zBlAj5eztpwwbjl9lyPG1DFOUEAIFDqxJB6ks","oC1ZN2NVsDm7zt4GNUhBgdUPrXwckWtQOJB0VQE2XRF8UQt9hodrIGw+FaDcWVjAwAsh","hsD7kAbPO2Dr78ZEBoZfHxQYHNYbwEogvIGjKSfOiNysBpaEL/acv8MODBhuUX7u00Bh","VVx6DZWlxHcDAxQEDl95AMZQAGqHLlSSFIanAnZWll0/f/8Bs2OcDB+5GavJVyGZtevs","rYdL9p2XQ6rZGcnKI54nZRj2uoMCAVr4K8JkQAKgJsdEYN12AbmYYSGqYGJk/NC8bO91","WHKUFRXgwace6ElDIF4PjHWHc3eeMZy98xSU8mB1mwE0FSQCU8ECZiZGVpi+yw9eLIfV","lUyMjIf+/f/Pu/bIlTtIdSX5hauo+RagxxMZfr2fwHB3IT/Dy4MMDI/BzTABaP2aAGzm",
"gPpN4gQDB1pmgIA+EAfcfvoGXl/mB1hXFuBxCLDs6oc26kBJZiIoxShLCqs9e/tp+vdf","v8ENB08Tdf9FwHKsMtxxTfvK/SGgbHfx3vNyoL2g7DjR30r74vqjV2yA6lXgbnI2WtoH","4yhEfGF4sAISSTcm9wOzDcidoE6lPTBLwRuyDMoJ5+DZagnLJIb/f3mh5edGcKoRs+5n","eHUUUgZxiIrhrK2wFchc7KwMmsByANjiAZUfoGzhCEpJIDlQowOYffqRC2RQS+f1x68H","Nx6/ygcqY9A7RMZAc5LcTS/zcLLZwcwB1evAzs/8pfsvwDu9yOplgRECzF4M8a7Gryw0","5NRB+sDtiC/3HjKcKeaDpgAEADVmNIDlsX4DqFPmCOvvMNxdkAAuX95dQFUPKnv06kEB","mQgNOLpV5QbQpAsrcz4QUC+AVJsgqxcgoNcBqQy5QIIdONUDALcn6c0dtMJ9AAAAAElF","TkSuQmCC"],
C=["R0lGODlhEAALAPQAAP///z2LqeLt8dvp7u7090GNqz2LqV+fuJ/F1IW2ycrf51aatHWs","waXJ14i4ys3h6FmctUCMqniuw+vz9eHs8fb5+meku+Tu8vT4+cfd5bbT3tbm7PH2+AAA","AAAAAAAAACH/C05FVFNDQVBFMi4wAwEAAAAh/hpDcmVhdGVkIHdpdGggYWpheGxvYWQu","aW5mbwAh+QQJCwAAACwAAAAAEAALAAAFLSAgjmRpnqSgCuLKAq5AEIM4zDVw03ve27if","DgfkEYe04kDIDC5zrtYKRa2WQgAh+QQJCwAAACwAAAAAEAALAAAFJGBhGAVgnqhpHIeR","vsDawqns0qeN5+y967tYLyicBYE7EYkYAgAh+QQJCwAAACwAAAAAEAALAAAFNiAgjoth","LOOIJAkiGgxjpGKiKMkbz7SN6zIawJcDwIK9W/HISxGBzdHTuBNOmcJVCyoUlk7CEAAh","+QQJCwAAACwAAAAAEAALAAAFNSAgjqQIRRFUAo3jNGIkSdHqPI8Tz3V55zuaDacDyIQ+",
"YrBH+hWPzJFzOQQaeavWi7oqnVIhACH5BAkLAAAALAAAAAAQAAsAAAUyICCOZGme1rJY","5kRRk7hI0mJSVUXJtF3iOl7tltsBZsNfUegjAY3I5sgFY55KqdX1GgIAIfkECQsAAAAs","AAAAABAACwAABTcgII5kaZ4kcV2EqLJipmnZhWGXaOOitm2aXQ4g7P2Ct2ER4AMul00k","j5g0Al8tADY2y6C+4FIIACH5BAkLAAAALAAAAAAQAAsAAAUvICCOZGme5ERRk6iy7qpy","HCVStA3gNa/7txxwlwv2isSacYUc+l4tADQGQ1mvpBAAIfkECQsAAAAsAAAAABAACwAA","BS8gII5kaZ7kRFGTqLLuqnIcJVK0DeA1r/u3HHCXC/aKxJpxhRz6Xi0ANAZDWa+kEAA7","AAAAAAAAAAAA"];b.settings.add("disqus.developer",{type:"bool"}).add("disqus.preview",
{type:"obj",rule:function(a){return a!=null&&typeof a.source=="string"&&typeof a.styles=="string"}}).add("thread.category",{type:["str","int"]}).add("thread.slug",{type:"str"}).add("thread.title",{type:"str"}).add("thread.url",{type:"str"}).add("thread.identifier",{type:["str","int"]}).add("thread.postsPerPage",{type:["str","int"]}).add("thread.moderatePosts",{type:"str",values:["all","none","anon"]}).add("thread.skipAuthRequest",{type:"bool"}).add("thread.sort",{type:"str",values:{oldest:1,newest:2,
best:3,hot:4,highlighted:5}}).add("thread.defaults.name",{type:"str"}).add("thread.defaults.email",{type:"str"}).add("thread.defaults.placeholder",{type:"str"}).add("thread.author.sig",{type:"str"}).add("forum.shortname",{type:"str"}).add("forum.apiKey",{type:"str"}).add("forum.facebook.key",{type:"str"}).add("ui.translations",{type:"obj"}).add("ui.container",{type:"str"}).add("request.sso.data",{type:"str"}).add("legacy.trackbacks",{type:"obj"}).add("legacy.thread.author.sig",{type:"str"}).add("legacy.sso.data",
{type:"str"}).add("realtime.host",{type:"str"}).add("realtime.port",{type:"int"});var z=r(new Date);b.extend({cache:{postboxBusy:{},buttonsToRestore:[],popupProfileCache:{},popupStatusCache:{},toggledReplies:{},postSharing:{},realtime:{interval:null,ongoing_request:null,prev_script:null,last_checked:null,newPosts:[]}},states:{edit:{},realtime:!1,noThirdPartyCookies:null,useLoginWindow:!1,loginDisabled:!1,metaViewport:function(){for(var a=0,b=t.length;a<b;a++)if(t[a].getAttribute("name")=="viewport")return!0;
return!1}(),isMobile:!1},curPageId:"dsq-comments",frames:{},config:{template:null},jsonData:null,isReady:!1,getShortname:function(){function a(b){var b=b.getAttribute?b.getAttribute("src"):b.src,c=[/https?:\/\/(www\.)?disqus\.com\/forums\/([\w_\-]+)/i,/https?:\/\/(www\.)?([\w_\-]+)\.disqus\.com/i,/https?:\/\/(www\.)?dev\.disqus\.org\/forums\/([\w_\-]+)/i,/https?:\/\/(www\.)?([\w_\-]+)\.dev\.disqus\.org/i],d=c.length;if(!b||b.substring(b.length-8)!="embed.js")return null;for(var e=0;e<d;e++){var f=
b.match(c[e]);if(f&&f.length&&f.length==3)return f[2]}return null}for(var b=m.getElementsByTagName("script"),c=b.length-1;c>=0;c--){var d=a(b[c]);if(d!==null)return d}return null},callback:function(a){var c=arguments.length>1?Array.prototype.slice.call(arguments,1):[];b.trigger(a,{args:c})},reset:function(a){v.push(a);b.defer(function(){return b.resettable},function(){var a=b.nodes.get("#"+b.config.container_id),d=v.pop();if(d)v=[],b.comm.reset(!0),b.jsonData=null,b.sandbox.invalidateGlobals(),b.resettable=
!1,b.config.page={},a.innerHTML="",b.trigger("thread.beforeReset"),b.unbindAll(),d.reload&&(c(d.config),g(),k(),p())})},updatePost:function(a,c){var d=b.jsonData.posts[a]||{};if(c)c.id=a,b.jsonData.posts[a]=b.extend(d,c),b.trigger("data.onPostUpdate",{id:a,data:c})},reload:function(a){b.require(b.config.json_url,b.config.page,!0,function(){u=!0;typeof a=="function"&&a()})},redraw:function(a){if(u||a)b.sandbox.invalidateGlobals(),a=b.nodes.get("#dsq-content"),a.innerHTML=b.renderBlock("thread"),b.frames=
[],b.dtpl.actions.fire("thread.initialize"),u=!1},initThread:function(c){function d(b){var c=a.onload;a.onload=typeof a.onload!="function"?b:function(){c&&c();b()}}function e(){var c,d;if(b.isReady){if(g&&clearInterval(g),m.getElementById(b.settings.get("ui.container")),c=m.getElementsByTagName("iframe"),d=m.getElementById("dsq-content"))for(var f=0,h=c.length;f<h;f++)c[f].style.width=d.offsetWidth}else g||(g=a.setInterval(e,500))}var f,g;b.browser.ie&&b.config.frame_theme!=="cnn2"&&d(e);b.trigger("loader.onReady");
f=m.getElementById("dsq-content")||m.createElement("div");f.id="dsq-content";f.style.display="none";m.getElementById(b.config.container_id).appendChild(f);b.container=m.getElementById("dsq-content");try{b.browser.ie6&&m.execCommand("BackgroundImageCache",!1,!0)}catch(i){}b.config.page.lazy="0";var k=b.partial(s,c),l=b.partial(b.require,b.config.json_url,b.config.page,!0,k);if(b.jsonData==null)return void l();b.defer(function(){var a=b.jsonData;return a&&(a.ready||a.lazy)},function(){if(b.jsonData.ready)return void k();
b.once("thread.topViewed",function(){l()})})}});c();g();k();p();(function(){function c(a,f){var g=i(e)[1];if(e&&d(g))return b.ready(function(){b.trigger("thread.topViewed")}),typeof f=="function"?f():!0;return!1}var e=m.getElementById(b.config.container_id);c()||b.events.debounce(a,"scroll",c,250)})()})(this);